// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconMdi:ethereum': typeof import('~icons/mdi/ethereum')['default']
    'IconMdi:linkBoxVariant': typeof import('~icons/mdi/link-box-variant')['default']
    'IconMdi:openInNew': typeof import('~icons/mdi/open-in-new')['default']
    'IconMdi:triangle': typeof import('~icons/mdi/triangle')['default']
    'IconMdi:twitterBox': typeof import('~icons/mdi/twitter-box')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:apps': typeof import('~icons/uil/apps')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
