// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconMdi:cardsDiamond': typeof import('~icons/mdi/cards-diamond')['default']
    'IconMdi:cardsDiamondOutline': typeof import('~icons/mdi/cards-diamond-outline')['default']
    'IconMdi:cardsDimond': typeof import('~icons/mdi/cards-dimond')['default']
    'IconMdi:check': typeof import('~icons/mdi/check')['default']
    'IconMdi:checkBold': typeof import('~icons/mdi/check-bold')['default']
    'IconMdi:checkCircleOutline': typeof import('~icons/mdi/check-circle-outline')['default']
    'IconMdi:currencyUsd': typeof import('~icons/mdi/currency-usd')['default']
    'IconMdi:diamond': typeof import('~icons/mdi/diamond')['default']
    'IconMdi:discord': typeof import('~icons/mdi/discord')['default']
    'IconMdi:discordAlt': typeof import('~icons/mdi/discord-alt')['default']
    'IconMdi:dotsTriange': typeof import('~icons/mdi/dots-triange')['default']
    'IconMdi:dotsTriangle': typeof import('~icons/mdi/dots-triangle')['default']
    'IconMdi:ethereum': typeof import('~icons/mdi/ethereum')['default']
    'IconMdi:etherium': typeof import('~icons/mdi/etherium')['default']
    'IconMdi:hexagram': typeof import('~icons/mdi/hexagram')['default']
    'IconMdi:linkBoxVariant': typeof import('~icons/mdi/link-box-variant')['default']
    'IconMdi:mdiCheckCircleOutline': typeof import('~icons/mdi/mdi-check-circle-outline')['default']
    'IconMdi:money': typeof import('~icons/mdi/money')['default']
    'IconMdi:octagram': typeof import('~icons/mdi/octagram')['default']
    'IconMdi:octagramOutline': typeof import('~icons/mdi/octagram-outline')['default']
    'IconMdi:octogram': typeof import('~icons/mdi/octogram')['default']
    'IconMdi:openInNew': typeof import('~icons/mdi/open-in-new')['default']
    'IconMdi:rhombus': typeof import('~icons/mdi/rhombus')['default']
    'IconMdi:triang': typeof import('~icons/mdi/triang')['default']
    'IconMdi:triange': typeof import('~icons/mdi/triange')['default']
    'IconMdi:triangle': typeof import('~icons/mdi/triangle')['default']
    'IconMdi:triangleDown': typeof import('~icons/mdi/triangle-down')['default']
    'IconMdi:TriangleDown': typeof import('~icons/mdi/-triangle-down')['default']
    'IconMdi:twitterBox': typeof import('~icons/mdi/twitter-box')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:apps': typeof import('~icons/uil/apps')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
