backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: /img
local_backend: true
collections:
  - name: "partner" # Used in routes, e.g., /admin/collections/blog
    label: "Partners" # Used in the UI
    label_singular: "Partner"
    folder: "content/partners" # The path to the folder where the documents are stored
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    identifier_field: name
    editor:
      preview: false
    view_groups:
    - label: Partner type
      field: type
    - label: Visible
      field: hidden

    fields: # The fields for each document, usually in front matter
      - { label: "Hidden", name: "hidden", widget: "boolean", default: true}
      - { label: "Partner name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - {
          label: "Partner type",
          name: "type",
          widget: "relation",
          collection: 'partner-type',
          search_fields: ["title"],
          display_fields:  ["title"],
          value_field: 'id'
        }
      - { label: "URL", name: "url", widget: "string", hint: "A link to website or social media profile", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Order", name: "order", widget: "number" ,  default: 0, hint: "Add a higher number to display first, leave at 0 for default order"}
  - name: "partner-type" # Used in routes, e.g., /admin/collections/blog
    label: "Partner types" # Used in the UI
    label_singular: "Partner type"
    hide: true
    folder: "content/partners-types" # The path to the folder where the documents are stored
    format: "frontmatter"
    create: false # Allow users to create new documents in this collection
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - { label: "Type name", name: "title", widget: "string" }
      - { label: "Type id", name: "id", widget: "string", hidden: true }
      - { label: "Order", name: "order", widget: "number" }
  - name: "speakers" # Used in routes, e.g., /admin/collections/blog
    label: "Speakers" # Used in the UI
    label_singular: "Speaker"
    hide: false
    folder: "content/speaker" # The path to the folder where the documents are stored
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: "Speaker name", name: "name", widget: "string" }
      - { label: "Speaker job/title", name: "title", widget: "string", required: false  }
      - { label: "Profile picture", name: "img", widget: "image", required: false  }
      - { label: "Twitter url", name: "twitter", widget: "string" , required: false }
      - { label: "Link", name: "url", widget: "string", hint: "link to company or persona website ", required: false  }
      - { label: "Highlight", name: "highlight", widget: "boolean", default: false, hint: "Add a drop shadow to highlight a speaker"}
      - { label: "Order", name: "order", widget: "number" ,  default: 0, hint: "Add a higher number to display first, leave at 0 for default order"}