backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: /img
local_backend: true
collections:
  - name: "partner" # Used in routes, e.g., /admin/collections/blog
    label: "Partners" # Used in the UI
    label_singular: "Partner"
    folder: "content/partners" # The path to the folder where the documents are stored
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    identifier_field: name
    editor:
      preview: false
    view_groups:
    - label: Partner type
      field: type
    - label: Visible
      field: hidden

    fields: # The fields for each document, usually in front matter
      - { label: "Hidden", name: "hidden", widget: "boolean", default: true}
      - { label: "Partner name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - {
          label: "Partner type",
          name: "type",
          widget: "relation",
          collection: 'partner-type',
          search_fields: ["title"],
          display_fields:  ["title"],
          value_field: 'id'
        }
      - { label: "URL", name: "url", widget: "string",pattern: ['^(https?:\/\/)?([\da-z\.-]+\.[a-z\.]{2,6}|[\d\.]+)([\/:?=&#]{1}[\da-z\.-]+)*[\/\?]?$', 'Please enter a valid URL'], hint: "A link to website or social media profile", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Order", name: "order", widget: "number" ,  default: 0, hint: "Add a higher number to display first, leave at 0 for default order"}
  - name: "partner-type" # Used in routes, e.g., /admin/collections/blog
    label: "Partner types" # Used in the UI
    label_singular: "Partner type"
    hide: true
    folder: "content/partners-types" # The path to the folder where the documents are stored
    format: "frontmatter"
    create: false # Allow users to create new documents in this collection
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - { label: "Type name", name: "title", widget: "string" }
      - { label: "Type id", name: "id", widget: "string", hidden: true }
      - { label: "Order", name: "order", widget: "number" }
  - name: "speakers" # Used in routes, e.g., /admin/collections/blog
    label: "Speakers" # Used in the UI
    label_singular: "Speaker"
    hide: false
    folder: "content/speaker" # The path to the folder where the documents are stored
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: "Keynote speaker", name: "keynote", widget: "boolean", default: false, required: false }
      - { label: "Panel speaker", name: "panel", widget: "boolean", default: false, required: false }
      - { label: "Speaker name", name: "name", widget: "string" }
      - { label: "Speaker job/title", name: "description", widget: "string", required: false  }
      - { label: "Profile picture", name: "img", widget: "image", required: false  }
      - { label: "Twitter url", name: "twitter", widget: "string",pattern: ['(https:\/\/twitter.com\/(?![a-zA-Z0-9_]+\/)([a-zA-Z0-9_]+))', 'Please enter a full URL'], required: false }
      - { label: "Link", name: "url", widget: "string", pattern: ['(http|ftp|https):\/\/([\w+?\.\w+])+([a-zA-Z0-9\~\!\@\#\$\%\^\&\*\(\)_\-\=\+\\\/\?\.\:\;\"\,]*)?', 'Please enter a valid URL'], hint: "link to company or persona website ", required: false  }
      - { label: "Order", name: "order", widget: "number" ,  default: 0, hint: "Add a higher number to display first, leave at 0 for default order"}
  - name: "faq" # Used in routes, e.g., /admin/collections/blog
    label: "FAQ's" # Used in the UI
    label_singular: "FAQ"
    hide: false
    folder: "content/faq" # The path to the folder where the documents are stored
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    editor:
      preview: true
    fields:
      - { label: "Hidden", name: "hidden", widget: "boolean", default: false} # The fields for each document, usually in front matter
      - {
          label: "Category",
          name: "category",
          widget: "select",
          multiple: true,
          min: 1,
          default: ["general"],
          options: ["general", "conference", "hack", "media"]
        }
      - { label: "Question", name: "title", widget: "string" }
      - { label: "Answer", name: "body", widget: "markdown"  }
      - { label: "Question order", name: "order", widget: "number" ,  default: 0, hint: "Will display in order from lowest (0) to highest"}
  - name: "bounty" # Used in routes, e.g., /admin/collections/blog
    label: "Bounties" # Used in the UI
    label_singular: "bounty"
    hide: false
    folder: "content/bounties" # The path to the folder where the documents are stored
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    editor:
      preview: true
    fields:
      - { label: "Hidden", name: "hidden", widget: "boolean", default: false} # The fields for each document, usually in front matter
      - { label: "Amount Or Pre-title", name: "pre_title", widget: "string"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle Or Company", name: "sub_title", widget: "string", required: false }
      - { label: "Description", name: "body", widget: "markdown"  }
      - { label: "Bounty order", name: "order", widget: "number" ,  default: 0, hint: "Add a higher number to display first, leave at 0 for default order"}
